// This file is generated by `cargo test -p skillhub-desktop generate_bindings`.
// Rust contracts in skillhub-core are the source of truth.

import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

// This file has been generated by Specta. Do not edit this file manually.
export type AgentClient = {
	id: string,
	kind: ClientKind,
	supported_os: OperatingSystem[],
	path_candidates: PathCandidate[],
	skill_marker: string,
	deployment: DeploymentCapability,
	call_policy: CallPolicy,
};

export type AgentProfile = {
	profile_version: number,
	research_date: string,
	official_references: string[],
	brand: string,
	clients: AgentClient[],
};

export type AppCommand = { type: "create_skill"; payload: CreateSkill } | { type: "save_skill_content"; payload: SaveSkillContent } | { type: "rename_skill"; payload: RenameSkill } | { type: "set_lifecycle"; payload: SetLifecycle } | { type: "set_metadata"; payload: SetMetadata } | { type: "set_trial"; payload: SetTrial } | { type: "create_combination"; payload: CreateCombination } | { type: "set_current_version"; payload: SetCurrentVersion } | { type: "pin_project_skill_version"; payload: PinProjectSkillVersion } | { type: "create_custom_agent"; payload: CreateCustomAgent } | { type: "update_custom_agent"; payload: UpdateCustomAgent } | { type: "remove_custom_agent"; payload: RemoveCustomAgent } | { type: "reset_profile_override"; payload: ResetProfileOverride } | { type: "set_profile_override"; payload: SetProfileOverride } | { type: "register_project"; payload: RegisterProject } | { type: "update_project"; payload: UpdateProject } | { type: "set_project_tags"; payload: SetProjectTags } | { type: "save_project_view"; payload: SaveProjectView } | { type: "write_shared_project_config"; payload: WriteSharedProjectConfig } | { type: "read_shared_project_config"; payload: ReadSharedProjectConfig } | { type: "run_initialization_scan"; payload: RunInitializationScan } | { type: "scan_targets"; payload: ScanTargets } | { type: "rescan_skill"; payload: RescanSkill } | { type: "cancel_operation"; payload: {
	operation_id: OperationId,
} } | { type: "acknowledge_recovery"; payload: {
	operation_id: OperationId,
} };

export type AppCommandResult = { type: "operation_summary"; payload: OperationSummary } | { type: "custom_agent"; payload: CustomAgent } | { type: "custom_agent_override"; payload: CustomAgentOverride } | { type: "project"; payload: Project } | { type: "saved_project_view"; payload: SavedProjectView } | { type: "shared_project_config"; payload: SharedProjectConfig } | { type: "scan_result"; payload: ScanResult };

export type AppEvent = { type: "operation_progress"; payload: OperationProgress } | { type: "operation_finished"; payload: OperationSummary } | { type: "facts_changed"; payload: FactsChanged };

export type AppQuery = { type: "get_skill"; payload: GetSkill } | { type: "list_versions"; payload: ListVersions } | { type: "diff_versions"; payload: DiffVersions } | { type: "list_combinations"; payload: ListCombinations } | { type: "search"; payload: SearchQuery } | { type: "get_bootstrap_snapshot" } | { type: "list_pending_items"; payload: ListPendingItems } | { type: "get_discovery_snapshot"; payload: GetDiscoverySnapshot } | { type: "list_custom_agents"; payload: ListCustomAgents } | { type: "list_projects"; payload: ListProjects } | { type: "list_saved_project_views"; payload: ListSavedProjectViews } | { type: "get_deployment_plan"; payload: GetDeploymentPlan };

export type AppQueryResult = { type: "skill"; payload: SkillResult } | { type: "versions"; payload: VersionResult[] } | { type: "version_diff"; payload: VersionDiffResult } | { type: "combinations"; payload: CombinationResult[] } | { type: "search_results"; payload: SearchHit[] } | { type: "bootstrap_snapshot"; payload: BootstrapSnapshot } | { type: "pending_items"; payload: PendingItem[] } | { type: "discovery_snapshot"; payload: DiscoverySnapshot } | { type: "custom_agents"; payload: CustomAgent[] } | { type: "projects"; payload: Project[] } | { type: "saved_project_views"; payload: SavedProjectView[] } | { type: "deployment_plan"; payload: DeploymentPlan };

export type BootstrapSnapshot = {
	skill_count: number,
	project_count: number,
	agent_count: number,
	deployed_count: number,
	deployment_categories: DeploymentChartCategory[],
	recent_operations: RecentOperationSummary[],
	pending: PendingSummary,
	last_scan_at: string | null,
	recovery_state: StartupRecoveryState,
};

export type CallPolicy = "automatic" | "user_selected" | "unknown";

export type ClientInstance = {
	profile_id: string,
	client_id: string,
	kind: ClientKind,
	supported_os: OperatingSystem[],
	client_presence: ClientPresence,
};

export type ClientKind = "cli" | "desktop" | "ide_extension" | "tui" | "headless" | "acp" | "web" | "mobile" | "bot";

export type ClientPresence = "Unknown";

export type CombinationResult = {
	name: string,
	members: SkillId[],
};

export type CreateCombination = {
	name: string,
	members: SkillId[],
};

export type CreateCustomAgent = {
	agent: CustomAgentDraft,
};

export type CreateSkill = {
	name: string,
	source_path: string,
};

export type CustomAgent = {
	id: string,
	display_name: string,
	directory: ResolvedPathGrant,
	profile: AgentProfile,
};

export type CustomAgentDraft = {
	id: string,
	display_name: string,
	directory: PathGrant,
	profile: AgentProfile,
};

export type CustomAgentOverride = {
	profile_id: string,
	directory: ResolvedPathGrant,
	profile: AgentProfile,
};

export type DeploymentCapability = {
	copy: boolean,
	symlink: boolean,
	junction: boolean,
	limitations?: string[],
};

export type DeploymentChartCategory = {
	dimension: DeploymentDimension,
	key: string,
	label_code: string,
	count: number,
};

export type DeploymentDimension = "agent" | "project";

/**
 *  The filesystem representation selected for one physical deployment target.
 *  It is selected from the target's declared capabilities.
 *  A symbolic link is preferred because it keeps a deployment connected to the
 *  selected library version.  Junctions are a Windows directory fallback and
 *  managed copies are the portable last resort.
 */
export type DeploymentMode = "symbolic_link" | "directory_junction" | "managed_copy";

export type DeploymentPlan = {
	skill_id: SkillId,
	version_id: VersionId,
	runtime_name: string,
	/**
	 *  For a single physical target this is its selected mode.  For a batch
	 *  with different capabilities, inspect each `TargetPlan::mode`.
	 */
	mode: DeploymentMode,
	targets: TargetPlan[],
	warnings: string[],
	conflicts: TargetConflict[],
};

/**
 *  API-facing deployment preview request.  The caller selects registered
 *  logical target IDs; filesystem paths and physical identities are resolved
 *  by the application boundary before constructing planner input.
 */
export type DeploymentPlanRequest = {
	skill_id: SkillId,
	version_id: VersionId,
	runtime_name: string,
	logical_target_ids: string[],
	mode_override: DeploymentMode | null,
};

export type DiffVersions = {
	left: VersionId,
	right: VersionId,
};

export type DirectoryPrecedence = "preferred" | "lower_priority_copy" | "may_coexist" | "unknown";

export type DiscoveredSkill = {
	root: string,
	relative_path: string,
	path: string,
	marker: string,
	marker_size: number,
	marker_modified_at: number,
	size: number,
	latest_modified_at: number,
	fingerprint: string,
	metadata_fingerprint: string,
};

export type DiscoverySnapshot = {
	generation: string,
	observed_at: string,
	instances: ClientInstance[],
	logical_targets: LogicalTarget[],
	physical_targets: PhysicalTarget[],
};

/**  Stable machine-readable failures returned by the application boundary. */
export type ErrorCode = "input.invalid" | "path.outside_allowed_root" | "object.not_found" | "deployment.target_exists" | "deployment.target_changed" | "deployment.symlink_not_supported" | "deployment.junction_not_supported" | "target.ownership_unknown" | "deployment.ownership_mismatch" | "deployment.security_check_blocked" | "operation.conflict" | "operation.id_reused_with_different_request" | "credential.unavailable" | "migration.required" | "database.newer_schema" | "internal.error" | "combination.nesting_not_allowed" | "catalog.invalid_metadata" | "requirements.invalid_declaration" | "agent_profile.invalid_capability";

/**  Facts observed for a runtime name already present in a physical target. */
export type ExistingOwnership = "managed" | "unknown" | "agent_builtin" | "plugin" | "other_tool";

export type FactsChanged = Record<string, never>;

/**  Registered logical target IDs for a side-effect-free deployment preview. */
export type GetDeploymentPlan = {
	request: DeploymentPlanRequest,
};

export type GetDiscoverySnapshot = null;

export type GetSkill = {
	skill_id: SkillId,
};

export type ListCombinations = null;

export type ListCustomAgents = null;

export type ListPendingItems = null;

export type ListProjects = null;

export type ListSavedProjectViews = null;

export type ListVersions = {
	skill_id: SkillId,
};

export type LogicalTarget = {
	id: string,
	profile_id: string,
	client_id: string,
	scope: TargetScope,
	path: string,
	marker: string,
	precedence: DirectoryPrecedence,
	exists: boolean,
	readable: boolean,
	writable: boolean,
	available: boolean,
	physical_id: string,
};

export type OperatingSystem = "windows" | "macos";

export type OperationId = string;

export type OperationPhase = "planned" | "prepared" | "applying" | "verifying" | "committed" | "needs_recovery" | "rolled_back";

export type OperationProgress = {
	operation_id: OperationId,
	phase: OperationPhase,
	completed: number,
	total: number,
	message_code: string,
};

export type OperationSummary = {
	operation_id: OperationId,
	phase: OperationPhase,
	message_code: string,
	error_code: ErrorCode | null,
};

export type PathCandidate = {
	path: string,
	scope: TargetScope,
	precedence: DirectoryPrecedence,
	marker: string,
};

/**  Opaque identifier issued by the native file picker. */
export type PathGrant = {
	grant_id: string,
};

/**
 *  Derived pending work. `message_code` is an i18n key, never a localized
 *  sentence persisted in the database or cache.
 */
export type PendingItem = {
	subject: SkillId,
	kind: PendingKind,
	code: string,
	message_code: string | null,
};

/**  A stable category for work the user may need to handle. */
export type PendingKind = "trial_due" | "security_finding" | "recovery";

export type PendingSummary = {
	total: number,
	by_kind: Partial<{ [key in PendingKind]: number }>,
};

export type PhysicalTarget = {
	id: string,
	path: string,
	exists: boolean,
	readable: boolean,
	writable: boolean,
	case_behavior: string,
	logical_target_ids: string[],
};

export type PinProjectSkillVersion = {
	project_id: ProjectId,
	skill_id: SkillId,
	version_id: VersionId,
};

export type PortableSource = string;

/**
 *  A registered project. `device_path` is deliberately device-local and is
 *  never part of the portable `.skillhub/project.json` representation.
 */
export type Project = {
	id: ProjectId,
	name: string,
	device_path: string,
	physical_id: string,
	logical: ProjectMetadata,
	tags: ProjectTag[],
	created_at: string,
	updated_at: string,
};

export type ProjectId = string;

export type ProjectMetadata = {
	identity_hint: string | null,
	note: string | null,
};

export type ProjectTag = {
	name: string,
};

export type ReadSharedProjectConfig = {
	project_id: ProjectId,
};

export type RecentOperationSummary = {
	operation_id: OperationId,
	kind: string,
	state: string,
	phase: OperationPhase,
	error_code: string | null,
	created_at: string,
};

export type RegisterProject = {
	project: Project,
};

export type RemoveCustomAgent = {
	id: string,
};

export type RenameSkill = {
	skill_id: SkillId,
	name: string,
};

export type RescanSkill = {
	scope_id: string,
	path: string,
};

export type ResetProfileOverride = {
	profile_id: string,
};

export type ResolvedPathGrant = {
	grant_id: string,
	path: string,
	operating_system: OperatingSystem,
};

export type RunInitializationScan = {
	scope_ids: string[],
};

export type SaveProjectView = {
	view: SavedProjectView,
};

export type SaveSkillContent = {
	skill_id: SkillId,
	source_path: string,
};

export type SavedProjectView = {
	id: string,
	name: string,
	all_tags: string[],
	any_tags: string[],
};

export type ScanGeneration = {
	generation: number,
	observed_at: number,
};

export type ScanIssue = {
	path: string,
	code: string,
};

export type ScanResult = {
	generation: ScanGeneration,
	roots: string[],
	discovered: DiscoveredSkill[],
	visited_paths: string[],
	reparsed_count: number,
	unchanged_count: number,
	errors: ScanIssue[],
};

export type ScanTargets = {
	scope_ids: string[],
};

export type SearchField = "DisplayName" | "RuntimeName" | "OriginalDescription" | "TranslatedDescription" | "UserNote" | "Tags" | "Author" | "License" | "Requirements" | "Markdown";

export type SearchHit = {
	skill_id: SkillId,
	skill_name: string,
	rank: number | null,
	highlighted_fields: SearchField[],
};

export type SearchQuery = {
	text: string,
	limit: number,
};

export type SetCurrentVersion = {
	skill_id: SkillId,
	version_id: VersionId,
};

export type SetLifecycle = {
	skill_id: SkillId,
	lifecycle: SkillLifecycle,
};

export type SetMetadata = {
	skill_id: SkillId,
	display_name: string | null,
	note: string | null,
	tags: string[],
	author: string | null,
	license: string | null,
};

export type SetProfileOverride = {
	profile_id: string,
	directory: PathGrant,
	profile: AgentProfile,
};

export type SetProjectTags = {
	project_id: ProjectId,
	tags: string[],
};

export type SetTrial = {
	skill_id: SkillId,
	due: [number, number, number] | null,
};

/**
 *  Portable project metadata. It intentionally has no path, content,
 *  deployment, credential, or device-specific fields.
 */
export type SharedProjectConfig = {
	schema_version: number,
	project_identity_hint: string,
	required_skills: SharedSkillRequirement[],
};

export type SharedSkillRequirement = {
	skill_id: SkillId,
	source: PortableSource,
	name: string,
	version_constraint: string | null,
	version_id: VersionId | null,
	content_identity: string | null,
	logical_agent_id: string | null,
	project_subdirectory: string | null,
	note: string | null,
};

export type SkillId = string;

export type SkillLifecycle = "Normal" | "Deprecated" | "Archived";

export type SkillResult = {
	skill_id: SkillId,
	display_name: string,
	runtime_name: string,
};

export type StartupRecoveryState = "clean" | "in_progress" | "needs_recovery";

/**  Names used by the operation executor to summarize the filesystem change. */
export type TargetChange = "create" | "no_op";

export type TargetConflict = {
	physical_target_id: string,
	target_path: string,
	runtime_name: string,
	reason: TargetConflictReason,
	existing_ownership: ExistingOwnership,
};

export type TargetConflictReason = "runtime_name_already_exists" | "ownership_unknown" | "managed_by_another_skill";

export type TargetPlan = {
	physical_target_id: string,
	logical_target_ids: string[],
	target_path: string,
	destination_path: string,
	source_path: string,
	runtime_name: string,
	skill_id: SkillId,
	version_id: VersionId,
	mode: DeploymentMode,
	change: TargetChange,
	warnings: string[],
	conflicts: TargetConflict[],
};

export type TargetScope = "global" | "project" | "extra";

export type UpdateCustomAgent = {
	agent: CustomAgentDraft,
};

export type UpdateProject = {
	project: Project,
};

export type VersionDiffResult = {
	added: string[],
	removed: string[],
	changed: string[],
};

export type VersionId = string;

export type VersionResult = {
	version_id: VersionId,
	skill_id: SkillId,
};

export type WriteSharedProjectConfig = {
	project_id: ProjectId,
	config: SharedProjectConfig,
};

export const appEventName = "app_event" as const;

export function executeCommand(command: AppCommand): Promise<AppCommandResult> {
  return invoke<AppCommandResult>("execute_command", { command });
}

export function queryApplication(query: AppQuery): Promise<AppQueryResult> {
  return invoke<AppQueryResult>("query_application", { query });
}

export function onAppEvent(handler: (event: AppEvent) => void): Promise<UnlistenFn> {
  return listen<AppEvent>(appEventName, ({ payload }) => handler(payload));
}
