// This file is generated by `cargo test -p skillhub-desktop generate_bindings`.
// Rust contracts in skillhub-core are the source of truth.

import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

// This file has been generated by Specta. Do not edit this file manually.
export type AppCommand = { type: "cancel_operation"; payload: {
	operation_id: OperationId,
} } | { type: "acknowledge_recovery"; payload: {
	operation_id: OperationId,
} };

export type AppCommandResult = { type: "operation_summary"; payload: OperationSummary };

export type AppEvent = { type: "operation_progress"; payload: OperationProgress } | { type: "operation_finished"; payload: OperationSummary } | { type: "facts_changed"; payload: FactsChanged };

export type AppQuery = { type: "get_bootstrap_snapshot" };

export type AppQueryResult = { type: "bootstrap_snapshot"; payload: BootstrapSnapshot };

export type BootstrapSnapshot = Record<string, never>;

/**  Stable machine-readable failures returned by the application boundary. */
export type ErrorCode = "input.invalid" | "path.outside_allowed_root" | "object.not_found" | "deployment.target_exists" | "target.ownership_unknown" | "deployment.security_check_blocked" | "operation.conflict" | "credential.unavailable" | "migration.required" | "database.newer_schema" | "internal.error";

export type FactsChanged = Record<string, never>;

export type OperationId = string;

export type OperationPhase = "planned" | "prepared" | "applying" | "verifying" | "committed" | "needs_recovery" | "rolled_back";

export type OperationProgress = {
	operation_id: OperationId,
	phase: OperationPhase,
	completed: number,
	total: number,
	message_code: string,
};

export type OperationSummary = {
	operation_id: OperationId,
	phase: OperationPhase,
	message_code: string,
	error_code: ErrorCode | null,
};

export const appEventName = "app_event" as const;

export function executeCommand(command: AppCommand): Promise<AppCommandResult> {
  return invoke<AppCommandResult>("execute_command", { command });
}

export function queryApplication(query: AppQuery): Promise<AppQueryResult> {
  return invoke<AppQueryResult>("query_application", { query });
}

export function onAppEvent(handler: (event: AppEvent) => void): Promise<UnlistenFn> {
  return listen<AppEvent>(appEventName, ({ payload }) => handler(payload));
}
