use std::sync::Arc;

#[cfg(test)]
use std::path::PathBuf;

use skillhub_core::{
    AppCommand, AppCommandResult, AppError, AppEvent, AppQuery, AppQueryResult, AppResult,
    ApplicationFacade, ErrorCode, Severity,
};
use tauri::{AppHandle, Emitter, State};

/// The only state exposed to Tauri commands. It deliberately accepts domain
/// envelopes instead of stringly-typed command names or ad-hoc payloads.
pub struct CommandBridge {
    facade: Arc<dyn ApplicationFacade>,
}

impl CommandBridge {
    pub fn new(facade: Arc<dyn ApplicationFacade>) -> Self {
        Self { facade }
    }

    pub async fn execute(&self, command: AppCommand) -> AppResult<AppCommandResult> {
        self.facade.execute(command).await
    }

    pub async fn query(&self, query: AppQuery) -> AppResult<AppQueryResult> {
        self.facade.query(query).await
    }
}

#[tauri::command]
async fn execute_command(
    bridge: State<'_, CommandBridge>,
    command: AppCommand,
) -> AppResult<AppCommandResult> {
    bridge.execute(command).await
}

#[tauri::command]
async fn query_application(
    bridge: State<'_, CommandBridge>,
    query: AppQuery,
) -> AppResult<AppQueryResult> {
    bridge.query(query).await
}

pub fn emit_app_event<R: tauri::Runtime>(app: &AppHandle<R>, event: AppEvent) -> tauri::Result<()> {
    app.emit("app_event", event)
}

pub fn run_with_facade(facade: Arc<dyn ApplicationFacade>) -> tauri::Result<()> {
    tauri::Builder::default()
        .manage(CommandBridge::new(facade))
        .invoke_handler(tauri::generate_handler![execute_command, query_application])
        .run(tauri::generate_context!())
}

struct UnconfiguredFacade;

#[async_trait::async_trait]
impl ApplicationFacade for UnconfiguredFacade {
    async fn execute(&self, _command: AppCommand) -> AppResult<AppCommandResult> {
        Err(AppError::new(ErrorCode::InternalError, Severity::Error))
    }

    async fn query(&self, _query: AppQuery) -> AppResult<AppQueryResult> {
        Err(AppError::new(ErrorCode::InternalError, Severity::Error))
    }
}

pub fn run() -> tauri::Result<()> {
    run_with_facade(Arc::new(UnconfiguredFacade))
}

#[cfg(test)]
fn generated_bindings_source() -> Result<String, Box<dyn std::error::Error>> {
    use skillhub_core::{
        AppCommand, AppCommandResult, AppEvent, AppQuery, AppQueryResult, ErrorCode,
        OperationPhase, OperationProgress, OperationSummary,
    };

    let types = specta::Types::default()
        .register::<AppCommand>()
        .register::<AppCommandResult>()
        .register::<AppQuery>()
        .register::<AppQueryResult>()
        .register::<AppEvent>()
        .register::<OperationPhase>()
        .register::<OperationProgress>()
        .register::<OperationSummary>()
        .register::<ErrorCode>();
    let contracts =
        specta_typescript::Typescript::default().export(&types, specta_serde::Format)?;

    Ok(format!(
        r#"// This file is generated by `cargo test -p skillhub-desktop generate_bindings`.
// Rust contracts in skillhub-core are the source of truth.

import {{ invoke }} from "@tauri-apps/api/core";
import {{ listen, type UnlistenFn }} from "@tauri-apps/api/event";

{contracts}
export const appEventName = "app_event" as const;

export function executeCommand(command: AppCommand): Promise<AppCommandResult> {{
  return invoke<AppCommandResult>("execute_command", {{ command }});
}}

export function queryApplication(query: AppQuery): Promise<AppQueryResult> {{
  return invoke<AppQueryResult>("query_application", {{ query }});
}}

export function onAppEvent(handler: (event: AppEvent) => void): Promise<UnlistenFn> {{
  return listen<AppEvent>(appEventName, ({{ payload }}) => handler(payload));
}}
"#
    ))
}

#[test]
fn generate_bindings() {
    let generated = generated_bindings_source().expect("generate TypeScript from Rust contracts");
    let destination = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/api/bindings.ts");
    std::fs::write(&destination, generated).expect("generated bindings destination");
    let generated = std::fs::read_to_string(destination).expect("generated bindings output");
    assert!(generated.contains("export type AppCommand"));
    assert!(generated.contains("export type AppQuery"));
    assert!(generated.contains("export type AppEvent"));
    assert!(generated.contains("export function executeCommand"));
    assert!(generated.contains("export function queryApplication"));
}

#[test]
fn command_bridge_forwards_typed_envelopes_to_injected_facade() {
    use std::sync::Mutex;

    use skillhub_core::{
        AppQueryResult, BootstrapSnapshot, OperationId, OperationPhase, OperationSummary,
    };

    struct RecordingFacade {
        commands: Mutex<Vec<AppCommand>>,
        queries: Mutex<Vec<AppQuery>>,
    }

    #[async_trait::async_trait]
    impl ApplicationFacade for RecordingFacade {
        async fn execute(&self, command: AppCommand) -> AppResult<AppCommandResult> {
            self.commands.lock().expect("commands mutex").push(command);
            Ok(AppCommandResult::OperationSummary(OperationSummary {
                operation_id: OperationId::new(),
                phase: OperationPhase::Prepared,
                message_code: "test.forwarded".into(),
                error_code: None,
            }))
        }

        async fn query(&self, query: AppQuery) -> AppResult<AppQueryResult> {
            self.queries.lock().expect("queries mutex").push(query);
            Ok(AppQueryResult::BootstrapSnapshot(BootstrapSnapshot {}))
        }
    }

    let facade = Arc::new(RecordingFacade {
        commands: Mutex::new(Vec::new()),
        queries: Mutex::new(Vec::new()),
    });
    let bridge = CommandBridge::new(facade.clone());
    let command = AppCommand::CancelOperation {
        operation_id: OperationId::new(),
    };

    tauri::async_runtime::block_on(async {
        bridge
            .execute(command.clone())
            .await
            .expect("command result");
        bridge
            .query(AppQuery::GetBootstrapSnapshot)
            .await
            .expect("query result");
    });

    assert_eq!(
        facade.commands.lock().expect("commands mutex").as_slice(),
        &[command]
    );
    assert_eq!(
        facade.queries.lock().expect("queries mutex").as_slice(),
        &[AppQuery::GetBootstrapSnapshot]
    );
}
