[package]
name = "skillhub-application"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[dependencies]
async-trait = "0.1"
skillhub-core = { path = "../skillhub-core", version = "0.1.0" }
skillhub-storage = { path = "../skillhub-storage", version = "0.1.0" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
